package prueba;
// Generated 18 dic 2023 10:56:59 by Hibernate Tools 6.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Ciclista generated by hbm2java
 */
public class Ciclista implements java.io.Serializable {

	private int dorsal;
	private Equipo equipo;
	private String nombre;
	private Integer edad;
	private Set etapas = new HashSet(0);
	private Set puertos = new HashSet(0);
	private Set llevars = new HashSet(0);

	public Ciclista() {
	}

	public Ciclista(int dorsal, Equipo equipo, String nombre, Integer edad, Set etapas, Set puertos, Set llevars) {
		this.dorsal = dorsal;
		this.equipo = equipo;
		this.nombre = nombre;
		this.edad = edad;
		this.etapas = etapas;
		this.puertos = puertos;
		this.llevars = llevars;
	}

	public int getDorsal() {
		return this.dorsal;
	}

	public void setDorsal(int dorsal) {
		this.dorsal = dorsal;
	}

	public Equipo getEquipo() {
		return this.equipo;
	}

	public void setEquipo(Equipo equipo) {
		this.equipo = equipo;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Integer getEdad() {
		return this.edad;
	}

	public void setEdad(Integer edad) {
		this.edad = edad;
	}

	public Set getEtapas() {
		return this.etapas;
	}

	public void setEtapas(Set etapas) {
		this.etapas = etapas;
	}

	public Set getPuertos() {
		return this.puertos;
	}

	public void setPuertos(Set puertos) {
		this.puertos = puertos;
	}

	public Set getLlevars() {
		return this.llevars;
	}

	public void setLlevars(Set llevars) {
		this.llevars = llevars;
	}

}
