package prueba;
// Generated 18 dic 2023 10:56:59 by Hibernate Tools 6.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Equipo generated by hbm2java
 */
public class Equipo implements java.io.Serializable {

	private String nomeq;
	private String director;
	private Set ciclistas = new HashSet(0);

	public Equipo() {
	}

	public Equipo(String nomeq, String director, Set ciclistas) {
		this.nomeq = nomeq;
		this.director = director;
		this.ciclistas = ciclistas;
	}

	public String getNomeq() {
		return this.nomeq;
	}

	public void setNomeq(String nomeq) {
		this.nomeq = nomeq;
	}

	public String getDirector() {
		return this.director;
	}

	public void setDirector(String director) {
		this.director = director;
	}

	public Set getCiclistas() {
		return this.ciclistas;
	}

	public void setCiclistas(Set ciclistas) {
		this.ciclistas = ciclistas;
	}

}
