package prueba;
// Generated 18 dic 2023 10:56:59 by Hibernate Tools 6.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Etapa generated by hbm2java
 */
public class Etapa implements java.io.Serializable {

	private int netapa;
	private Ciclista ciclista;
	private Integer km;
	private String salida;
	private String llegada;
	private Set puertos = new HashSet(0);
	private Set llevars = new HashSet(0);

	public Etapa() {
	}

	public Etapa(int netapa, Ciclista ciclista, Integer km, String salida, String llegada, Set puertos, Set llevars) {
		this.netapa = netapa;
		this.ciclista = ciclista;
		this.km = km;
		this.salida = salida;
		this.llegada = llegada;
		this.puertos = puertos;
		this.llevars = llevars;
	}

	public int getNetapa() {
		return this.netapa;
	}

	public void setNetapa(int netapa) {
		this.netapa = netapa;
	}

	public Ciclista getCiclista() {
		return this.ciclista;
	}

	public void setCiclista(Ciclista ciclista) {
		this.ciclista = ciclista;
	}

	public Integer getKm() {
		return this.km;
	}

	public void setKm(Integer km) {
		this.km = km;
	}

	public String getSalida() {
		return this.salida;
	}

	public void setSalida(String salida) {
		this.salida = salida;
	}

	public String getLlegada() {
		return this.llegada;
	}

	public void setLlegada(String llegada) {
		this.llegada = llegada;
	}

	public Set getPuertos() {
		return this.puertos;
	}

	public void setPuertos(Set puertos) {
		this.puertos = puertos;
	}

	public Set getLlevars() {
		return this.llevars;
	}

	public void setLlevars(Set llevars) {
		this.llevars = llevars;
	}

}
