package prueba;
// Generated 18 dic 2023 10:56:59 by Hibernate Tools 6.3.1.Final

/**
 * Llevar generated by hbm2java
 */
public class Llevar implements java.io.Serializable {

	private LlevarId id;
	private Maillot maillot;
	private Ciclista ciclista;
	private Etapa etapa;

	public Llevar() {
	}

	public Llevar(LlevarId id, Maillot maillot, Ciclista ciclista, Etapa etapa) {
		this.id = id;
		this.maillot = maillot;
		this.ciclista = ciclista;
		this.etapa = etapa;
	}

	public LlevarId getId() {
		return this.id;
	}

	public void setId(LlevarId id) {
		this.id = id;
	}

	public Maillot getMaillot() {
		return this.maillot;
	}

	public void setMaillot(Maillot maillot) {
		this.maillot = maillot;
	}

	public Ciclista getCiclista() {
		return this.ciclista;
	}

	public void setCiclista(Ciclista ciclista) {
		this.ciclista = ciclista;
	}

	public Etapa getEtapa() {
		return this.etapa;
	}

	public void setEtapa(Etapa etapa) {
		this.etapa = etapa;
	}

}
