package prueba;
// Generated 18 dic 2023 10:56:59 by Hibernate Tools 6.3.1.Final

/**
 * LlevarId generated by hbm2java
 */
public class LlevarId implements java.io.Serializable {

	private String codigo;
	private int dorsal;
	private int netapa;

	public LlevarId() {
	}

	public LlevarId(String codigo, int dorsal, int netapa) {
		this.codigo = codigo;
		this.dorsal = dorsal;
		this.netapa = netapa;
	}

	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	public int getDorsal() {
		return this.dorsal;
	}

	public void setDorsal(int dorsal) {
		this.dorsal = dorsal;
	}

	public int getNetapa() {
		return this.netapa;
	}

	public void setNetapa(int netapa) {
		this.netapa = netapa;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LlevarId))
			return false;
		LlevarId castOther = (LlevarId) other;

		return ((this.getCodigo() == castOther.getCodigo()) || (this.getCodigo() != null
				&& castOther.getCodigo() != null && this.getCodigo().equals(castOther.getCodigo())))
				&& (this.getDorsal() == castOther.getDorsal()) && (this.getNetapa() == castOther.getNetapa());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCodigo() == null ? 0 : this.getCodigo().hashCode());
		result = 37 * result + this.getDorsal();
		result = 37 * result + this.getNetapa();
		return result;
	}

}
