package prueba;
// Generated 18 dic 2023 10:56:59 by Hibernate Tools 6.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Maillot generated by hbm2java
 */
public class Maillot implements java.io.Serializable {

	private String codigo;
	private String tipo;
	private String color;
	private Integer premio;
	private Set llevars = new HashSet(0);

	public Maillot() {
	}

	public Maillot(String codigo, String tipo, String color, Integer premio, Set llevars) {
		this.codigo = codigo;
		this.tipo = tipo;
		this.color = color;
		this.premio = premio;
		this.llevars = llevars;
	}

	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public String getColor() {
		return this.color;
	}

	public void setColor(String color) {
		this.color = color;
	}

	public Integer getPremio() {
		return this.premio;
	}

	public void setPremio(Integer premio) {
		this.premio = premio;
	}

	public Set getLlevars() {
		return this.llevars;
	}

	public void setLlevars(Set llevars) {
		this.llevars = llevars;
	}

}
